server:
  port: 8080
  servlet:
    context-path: /Onionn

spring:
 datasource:
   url: "jdbc:mysql://localhost:3306/du_an2"
   username: root
   password: 123456
 mvc:
   view:
     prefix: /WEB-INF/views/
     suffix: .jsp
